import crypto from 'crypto';

const ALGORITHM = 'aes-256-gcm';
const VERSION = 1;

/**
 * Encrypts a string using AES-256-GCM
 * @returns Format: `v{VERSION}:{ivHex}:{authTagHex}:{ciphertextHex}`
 */
export function encryptToken(text: string, hexKey: string): string {
  if (!text) return text;
  
  const key = Buffer.from(hexKey, 'hex');
  if (key.length !== 32) {
    throw new Error('Encryption key must be exactly 32 bytes (64 hex characters)');
  }

  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);

  const encrypted = Buffer.concat([cipher.update(text, 'utf8'), cipher.final()]);
  const authTag = cipher.getAuthTag();

  return `v${VERSION}:${iv.toString('hex')}:${authTag.toString('hex')}:${encrypted.toString('hex')}`;
}

/**
 * Decrypts a token generated by encryptToken
 */
export function decryptToken(encryptedText: string, hexKey: string): string {
  if (!encryptedText) return encryptedText;

  const key = Buffer.from(hexKey, 'hex');
  if (key.length !== 32) {
    throw new Error('Encryption key must be exactly 32 bytes (64 hex characters)');
  }

  const parts = encryptedText.split(':');
  if (parts.length !== 4 || parts[0] !== `v${VERSION}`) {
    throw new Error('Invalid encrypted token format or version mismatch');
  }

  const [, ivHex, authTagHex, ciphertextHex] = parts;

  const iv = Buffer.from(ivHex, 'hex');
  const authTag = Buffer.from(authTagHex, 'hex');
  const ciphertext = Buffer.from(ciphertextHex, 'hex');

  const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(authTag);

  const decrypted = Buffer.concat([decipher.update(ciphertext), decipher.final()]);
  return decrypted.toString('utf8');
}
